# Generated by Django 4.0.5 on 2022-07-05 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
