# Generated by Django 4.0.5 on 2022-07-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0002_category_rename_text_event_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
