# Generated by Django 4.0.5 on 2022-07-07 00:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0004_county_remove_event_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Location',
        ),
        migrations.AddField(
            model_name='county',
            name='Location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='county',
            name='title',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county', to='Hangouts.county'),
        ),
    ]
