# Generated by Django 4.0.5 on 2022-07-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0005_remove_event_location_county_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='Location',
        ),
        migrations.AddField(
            model_name='event',
            name='Location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
