# Generated by Django 4.0.5 on 2022-07-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0006_remove_county_location_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Location',
            field=models.CharField(max_length=300),
        ),
    ]
