"""
Django settings for Events project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
import cloudinary
import cloudinary.uploader
import cloudinary.api


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s&7hi)kx)vb_*^k9s+v7$y!3^pe9kvpmd(m_trb^s3z&ctvl3_'

# Consumer_Key= 'U9LnDjlbL5Np2j5ZEscZaLHjmkemDfGv'
# Consumer_Secret= 'kYKndGNDbSGD1V4W'
# 'HddrNBQHbDpK6jLZ/EpJPnZQbZ7E+xffklFZrBYRk5goRKb+e5AM/0e1kUWBFZG6D3ydd3IwodPdv9hAZhkF3t+blHXBIZfg7HNJo3x5DMNF6eTGADPBFCjQ7G2bJWnTdN8C0kVhFLR5lDUoZThO2NPqIZZOsyrYg5GU6CPgD4x0weGxJV8uyL0yjVXhvV2k0fKT++kDVdknIZ67UMwovPiXFOxcojh8Pp83McBSbVP9/tXtTfK2Xw2W8q4x6VBVGEGbnTpNYhqBngfVLFe3sq85lBjNWlkxCicgCpvF8bmZ9kx3obSKbNtp5Lgzs6j15jb477NoXuitFqS9Km7hlA=='
# Pass_Key='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
# bsn_short_code='174379'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
#

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'Hangouts',
    'corsheaders',
    # 'cloudinary',
    'cloudinary_storage',
    'cloudinary',
    'django_filters',
       
]

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dm2xeskmd',
    'API_KEY': '991167433474882',
    'API_SECRET': 'i1z8gFqlEV2BbtAvmIYR90DANCY'
}

# cloudinary.config(
#     cloud_name = 'dm2xeskmd',
#     api_key =  '991167433474882',
#     api_secret = 'i1z8gFqlEV2BbtAvmIYR90DANCY'
# )
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
   
    
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'Events.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Events.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'DISABLE_SERVER_SIDE_CURSORS': True,
        'NAME': 'hangouts1',
        'USER': 'wamaitha',
    'PASSWORD':'hangouts2021',
    }
}

# multi user authentication
# AUTH_USER_MODEL='Hangouts.user'
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'








